name: Run news bot

on:
  schedule:
    - cron: '0 13,18 * * 1-5'  # Every weekday at 13:00 and 18:00 UTC (16:00 и 21:00 МСК)
  workflow_dispatch:

jobs:
  run-news-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID_1: ${{ secrets.CHANNEL_ID_1 }}
          CHANNEL_ID_2: ${{ secrets.CHANNEL_ID_2 }}
          PROXY: ${{ secrets.PROXY }}
        run: |
          python bot.py
